window.PRECAR_CITIES = [
  { id: "", name: "Todo o Brasil", uf: "", slug: "", ipva: 0.04 },
  { id: "sp-sao-paulo", name: "São Paulo", uf: "SP", slug: "sp-sao-paulo", ipva: 0.04 },
  { id: "rj-rio-de-janeiro", name: "Rio de Janeiro", uf: "RJ", slug: "rj-rio-de-janeiro", ipva: 0.04 },
  { id: "mg-belo-horizonte", name: "Belo Horizonte", uf: "MG", slug: "mg-belo-horizonte", ipva: 0.04 },
  { id: "pr-curitiba", name: "Curitiba", uf: "PR", slug: "pr-curitiba", ipva: 0.035 },
  { id: "rs-porto-alegre", name: "Porto Alegre", uf: "RS", slug: "rs-porto-alegre", ipva: 0.03 },
  { id: "sc-florianopolis", name: "Florianópolis", uf: "SC", slug: "sc-florianopolis", ipva: 0.02 },
  { id: "sc-joinville", name: "Joinville", uf: "SC", slug: "sc-joinville", ipva: 0.02 },
  { id: "ba-salvador", name: "Salvador", uf: "BA", slug: "ba-salvador", ipva: 0.025 },
  { id: "pe-recife", name: "Recife", uf: "PE", slug: "pe-recife", ipva: 0.0375 },
  { id: "ce-fortaleza", name: "Fortaleza", uf: "CE", slug: "ce-fortaleza", ipva: 0.03 },
  { id: "df-brasilia", name: "Brasília", uf: "DF", slug: "df-brasilia", ipva: 0.035 },
  { id: "go-goiania", name: "Goiânia", uf: "GO", slug: "go-goiania", ipva: 0.0375 },
  { id: "am-manaus", name: "Manaus", uf: "AM", slug: "am-manaus", ipva: 0.03 },
  { id: "pa-belem", name: "Belém", uf: "PA", slug: "pa-belem", ipva: 0.025 },
  { id: "es-vitoria", name: "Vitória", uf: "ES", slug: "es-vitoria", ipva: 0.02 },
  { id: "mt-cuiaba", name: "Cuiabá", uf: "MT", slug: "mt-cuiaba", ipva: 0.03 },
  { id: "ms-campo-grande", name: "Campo Grande", uf: "MS", slug: "ms-campo-grande", ipva: 0.035 },
  { id: "rn-natal", name: "Natal", uf: "RN", slug: "rn-natal", ipva: 0.03 },
  { id: "pb-joao-pessoa", name: "João Pessoa", uf: "PB", slug: "pb-joao-pessoa", ipva: 0.025 },
  { id: "al-maceio", name: "Maceió", uf: "AL", slug: "al-maceio", ipva: 0.025 },
  { id: "se-aracaju", name: "Aracaju", uf: "SE", slug: "se-aracaju", ipva: 0.025 },
  { id: "pi-teresina", name: "Teresina", uf: "PI", slug: "pi-teresina", ipva: 0.025 },
  { id: "ma-sao-luis", name: "São Luís", uf: "MA", slug: "ma-sao-luis", ipva: 0.025 },
  { id: "to-palmas", name: "Palmas", uf: "TO", slug: "to-palmas", ipva: 0.02 },
  { id: "ro-porto-velho", name: "Porto Velho", uf: "RO", slug: "ro-porto-velho", ipva: 0.03 },
  { id: "ac-rio-branco", name: "Rio Branco", uf: "AC", slug: "ac-rio-branco", ipva: 0.02 },
  { id: "ap-macapa", name: "Macapá", uf: "AP", slug: "ap-macapa", ipva: 0.03 },
  { id: "rr-boa-vista", name: "Boa Vista", uf: "RR", slug: "rr-boa-vista", ipva: 0.03 },
  { id: "mg-uberlandia", name: "Uberlândia", uf: "MG", slug: "mg-uberlandia", ipva: 0.04 },
  { id: "sp-campinas", name: "Campinas", uf: "SP", slug: "sp-campinas", ipva: 0.04 },
  { id: "sp-santos", name: "Santos", uf: "SP", slug: "sp-santos", ipva: 0.04 },
  { id: "sp-ribeirao-preto", name: "Ribeirão Preto", uf: "SP", slug: "sp-ribeirao-preto", ipva: 0.04 },
  { id: "pr-londrina", name: "Londrina", uf: "PR", slug: "pr-londrina", ipva: 0.035 }
];
